### 2.2 Skalenniveau und Datentypen

In [2]:
import pandas as pd
data = {'month': ['Jan', 'Feb', 'Mar'],
        'temp': [-5, 2, 3],
         'below_zero': [True, False, False]}
df = pd.DataFrame(data)
print(df)

  month  temp  below_zero
0   Jan    -5        True
1   Feb     2       False
2   Mar     3       False

In [13]:
# Welches Skalenniveau besitzen die Variablen im obigen Beispiel?

month: Nominalskala
temp: Metrische Skala (Intervallskala)
below_zero: Nominalskala

In [ ]:
# Sind die Variablen stetig oder diskret?

month: diskret
temp: stetig
below_zero: diskret

In [ ]:
# Was ist der Datentyp jeder einzelnen Spalte?

In [19]:
df.dtypes

month         object
temp           int64
below_zero      bool
dtype: object

In [21]:
#Erweitere das Python-Dictionary und erstelle eine neue Zeile mit den Werten ('Apr', 5, False) erstelle eine neue Spalte year mit den Werten (2020, 2020, 2020, 2020)

In [25]:
df.loc[3] = ['Apr', 5, False]

In [29]:
df['year'] = [2020, 2020, 2020, 2020]

In [35]:
df

  month  temp  below_zero  year
0   Jan    -5        True  2020
1   Feb     2       False  2020
2   Mar     3       False  2020
3   Apr     5       False  2020

### 2.3 Exkurs: Datenrundreise

In [112]:
df = pd.read_csv("../data/Library_Usage_Small.csv")

In [133]:
df.to_json("../data/Library_Usage_Small.json", index=False)

In [135]:
df = pd.read_json("../data/Library_Usage_Small.json")

In [137]:
df.to_html("../data/Library_Usage_Small.html", index=False)

In [139]:
df = pd.read_html("../data/Library_Usage_Small.html")
df = df[0]

In [141]:
df.to_excel("../data/Library_Usage_Small.xlsx", index=False)

In [143]:
df = pd.read_excel("../data/Library_Usage_Small.xlsx")

In [145]:
df.to_csv("../data/Library_usage_Small_new.csv", index=False)

In [147]:
df1 = pd.read_csv("../data/Library_Usage_Small.csv")
df2 = pd.read_csv("../data/Library_Usage_Small_new.csv")

In [149]:
df1.equals(df2)

True

### 2.4 Exkurs: Arbeitsspeicher

In [152]:
# Finde heraus, wie viel freier Arbeitsspeicher Dein Computer hat (Das Betriebssystem und Hintergrundprogramme verbrauchen auch RAM).

### 2.5 Fallstudie: Feature Engineering

In [5]:
import pandas as pd
df = pd.read_csv("../data/Library_Usage.csv",low_memory=False)
df.columns

Index(['Patron Type Definition', 'Total Checkouts', 'Total Renewals',
       'Age Range', 'Home Library Definition', 'Circulation Active Month',
       'Circulation Active Year', 'Notice Preference Definition',
       'Provided Email Address', 'Year Patron Registered',
       'Within San Francisco County'],
      dtype='object')

In [16]:
df.head()

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,Senior,5,0,75 years and over,Main,Nov,2022,Email,True,2015,False
1,Adult,0,0,45 to 54 years,Main,Jul,2023,Email,True,2019,False
2,Adult,0,0,55 to 59 years,Western Addition,Mar,2024,Email,True,2022,False
3,Welcome,1,1,20 to 24 years,Richmond,Aug,2022,Email,True,2022,False
4,Senior,0,0,65 to 74 years,Sunset,Mar,2024,Print,False,2023,False

In [22]:
df['Circulation Active Year'] = pd.to_numeric(
  df['Circulation Active Year'], errors='coerce'
)

In [26]:
df['Circulation Active Month'] = pd.to_datetime(
    df['Circulation Active Month'],
    errors='coerce',
    format="%b"
)

In [28]:
df['Circulation Active Month'] = df['Circulation Active Month'].dt.month

In [30]:
df

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,Senior,5,0,75 years and over,Main,11.0,2022.0,Email,True,2015,False
1,Adult,0,0,45 to 54 years,Main,7.0,2023.0,Email,True,2019,False
2,Adult,0,0,55 to 59 years,Western Addition,3.0,2024.0,Email,True,2022,False
3,Welcome,1,1,20 to 24 years,Richmond,8.0,2022.0,Email,True,2022,False
4,Senior,0,0,65 to 74 years,Sunset,3.0,2024.0,Print,False,2023,False
...,...,...,...,...,...,...,...,...,...,...,...
450354,Digital Access Card,0,0,35 to 44 years,Ingleside,NaN,NaN,Email,False,2023,Null
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,8.0,2022.0,Print,False,2022,Null
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,8.0,2022.0,Print,False,2022,Null
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,4.0,2022.0,Print,False,2022,Null
450358,Digital Access Card,0,0,65 to 74 years,Bayview,4.0,2023.0,Email,False,2023,Null

In [34]:
df['Membership Duration'] = (df['Circulation Active Year'] - df['Year Patron Registered'])*12 + df['Circulation Active Month']

In [36]:
df

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
0,Senior,5,0,75 years and over,Main,11.0,2022.0,Email,True,2015,False,95.0
1,Adult,0,0,45 to 54 years,Main,7.0,2023.0,Email,True,2019,False,55.0
2,Adult,0,0,55 to 59 years,Western Addition,3.0,2024.0,Email,True,2022,False,27.0
3,Welcome,1,1,20 to 24 years,Richmond,8.0,2022.0,Email,True,2022,False,8.0
4,Senior,0,0,65 to 74 years,Sunset,3.0,2024.0,Print,False,2023,False,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450354,Digital Access Card,0,0,35 to 44 years,Ingleside,NaN,NaN,Email,False,2023,Null,NaN
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,8.0,2022.0,Print,False,2022,Null,8.0
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,8.0,2022.0,Print,False,2022,Null,8.0
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,4.0,2022.0,Print,False,2022,Null,4.0
450358,Digital Access Card,0,0,65 to 74 years,Bayview,4.0,2023.0,Email,False,2023,Null,4.0

In [42]:
df['Membership Duration'] = df['Membership Duration'].fillna(0)

In [44]:
df

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
0,Senior,5,0,75 years and over,Main,11.0,2022.0,Email,True,2015,False,95.0
1,Adult,0,0,45 to 54 years,Main,7.0,2023.0,Email,True,2019,False,55.0
2,Adult,0,0,55 to 59 years,Western Addition,3.0,2024.0,Email,True,2022,False,27.0
3,Welcome,1,1,20 to 24 years,Richmond,8.0,2022.0,Email,True,2022,False,8.0
4,Senior,0,0,65 to 74 years,Sunset,3.0,2024.0,Print,False,2023,False,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450354,Digital Access Card,0,0,35 to 44 years,Ingleside,NaN,NaN,Email,False,2023,Null,0.0
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,8.0,2022.0,Print,False,2022,Null,8.0
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,8.0,2022.0,Print,False,2022,Null,8.0
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,4.0,2022.0,Print,False,2022,Null,4.0
450358,Digital Access Card,0,0,65 to 74 years,Bayview,4.0,2023.0,Email,False,2023,Null,4.0

### 2.6 Filtern

In [47]:
df_filtered = df

In [51]:
df_filtered['Age Range'].unique()

array(['75 years and over', '45 to 54 years', '55 to 59 years',
       '20 to 24 years', '65 to 74 years', '10 to 19 years',
       '25 to 34 years', '60 to 64 years', '35 to 44 years',
       '0 to 9 years', 'Null'], dtype=object)

Filtere den Datensatz nach Kindern unter 10 Jahren. Wie viele Einträge erhältst Du?

In [67]:
child_filter = df_filtered['Age Range'] == '0 to 9 years'
df_filtered.loc[child_filter]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
14,Teacher Card,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2023,False,0.0
1067,Adult,0,0,0 to 9 years,Richmond,12.0,2022.0,Phone,False,2022,False,12.0
1487,Juvenile,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2020,False,0.0
1488,Juvenile,0,0,0 to 9 years,Main,NaN,NaN,Email,True,2020,False,0.0
1491,Juvenile,0,0,0 to 9 years,Main,6.0,2023.0,Email,True,2017,False,78.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450241,Juvenile,0,0,0 to 9 years,Bernal Heights,NaN,NaN,Email,True,2022,Null,0.0
450244,Juvenile,2,2,0 to 9 years,Bayview,10.0,2023.0,Email,False,2023,Null,10.0
450245,Juvenile,0,0,0 to 9 years,Bayview,NaN,NaN,Email,False,2023,Null,0.0
450246,Juvenile,2,2,0 to 9 years,Bayview,10.0,2023.0,Email,False,2023,Null,10.0
450247,Juvenile,11,15,0 to 9 years,Bayview,3.0,2022.0,Email,True,2022,Null,3.0

Gibt es Personen mit mehr als 20000 Ausleihen?

In [77]:
ausleihen_filter = df_filtered['Total Checkouts'] > 20000
df_filtered[ausleihen_filter]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
60282,Senior,20561,1021,65 to 74 years,Main,3.0,2024.0,Phone,False,2004,True,243.0
60622,Senior,23134,617,65 to 74 years,Main,3.0,2024.0,Print,False,2003,True,255.0
60994,Senior,21890,16,75 years and over,Main,1.0,2023.0,Email,True,2005,True,217.0
179460,Adult,35176,62,25 to 34 years,Sunset,3.0,2024.0,Email,True,2010,True,171.0
234329,Adult,23345,6458,55 to 59 years,Chinatown,3.0,2024.0,Email,True,2003,True,255.0
234381,Adult,24386,387,45 to 54 years,Chinatown,3.0,2024.0,Phone,False,2003,True,255.0
293994,Adult,39743,659,60 to 64 years,Ortega,3.0,2024.0,Email,True,2003,True,255.0

In [82]:
ausleihen_filter.value_counts()

Total Checkouts
False    450352
True          7
Name: count, dtype: int64

Wie viele Personen stammen aus dem Stadtteil (Richmond)?

In [89]:
richmond_filter = df_filtered['Home Library Definition'] == 'Richmond'
richmond_filter.value_counts()

Home Library Definition
False    428926
True      21433
Name: count, dtype: int64

Wie viele Prozent der Beobachtungen haben eine Membership Duration von Null Monaten?

In [116]:
percent_missing = df_filtered['Membership Duration'].isnull().sum() * 100 / len(df)
print(percent_missing)

0.0

### 2.7 Datentypen

Was unterscheidet den Wert None vom Wert "None"? Was den Wert 5 vom Wert "5"? Was den Wert "NaN" vom Wert NaN? Ist True und "True" das gleiche?

"None" ist ein String, None ein wirklich fehlender Wert. 5 ist ein Integer, "5" ein String. "NaN" = String, NaN fehlender Wert. True ist boolean, "True" ein String.

In [124]:
print(type(x))

<class 'int'>

In [130]:
x = None

In [132]:
print(type(x))

<class 'NoneType'>

### 2.7 Datentypen

Welche Spalten enthalten alles fehlende Werte?

In [196]:
df = pd.read_csv("../data/Library_Usage.csv", low_memory=False, na_values="Null")
print(df.isnull().any())

Patron Type Definition          False
Total Checkouts                 False
Total Renewals                  False
Age Range                        True
Home Library Definition          True
Circulation Active Month         True
Circulation Active Year          True
Notice Preference Definition     True
Provided Email Address          False
Year Patron Registered          False
Within San Francisco County      True
dtype: bool

In [200]:
df.shape

(450359, 11)

Lies den Datensatz ein und erstelle einen DataFrame der keine Beobachtungen mit fehlenden Werten mehr enthält.

In [162]:
df_cleaned = df.dropna()

In [202]:
df_cleaned.shape

(406993, 11)

Speichere diesen unter dem Namen Library_Usage_Clean.csv ab.

In [166]:
df_cleaned.to_csv("../data/Library_Usage_Clean.csv", index=False)

Wie viele Beobachtungen wurden dabei entfernt?

In [182]:
entfernt = len(df.index) - len(df_cleaned.index)
print(f"Es wurden {entfernt} Beobachtungen entfernt.")

Es wurden 43366 Beobachtungen entfernt.

### 2.9 Pandas Funktionen

Schau Dir die Dokumentation für die Funktion head() hier an. Wie kannst Du Dir die ersten 100
 Zeilen anzeigen lassen?

In [188]:
df.head(100)

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,Senior,5,0,75 years and over,Main,Nov,2022.0,Email,True,2015,False
1,Adult,0,0,45 to 54 years,Main,Jul,2023.0,Email,True,2019,False
2,Adult,0,0,55 to 59 years,Western Addition,Mar,2024.0,Email,True,2022,False
3,Welcome,1,1,20 to 24 years,Richmond,Aug,2022.0,Email,True,2022,False
4,Senior,0,0,65 to 74 years,Sunset,Mar,2024.0,Print,False,2023,False
...,...,...,...,...,...,...,...,...,...,...,...
95,Senior,81,37,75 years and over,Main,Jun,2023.0,Email,True,2003,False
96,Senior,0,0,65 to 74 years,Main,Oct,2023.0,NaN,False,2022,False
97,Senior,0,0,65 to 74 years,Main,Mar,2024.0,Email,True,2019,False
98,Senior,0,0,65 to 74 years,Main,Mar,2024.0,Email,True,2023,False
99,Senior,1,0,75 years and over,Main,Mar,2020.0,Email,True,2015,False

In [192]:
df.shape

(450359, 11)