# Modul 2_1 Aufgabe

In [200]:
import pandas as pd
import requests

In [181]:
#import json

# url = "https://www.bibsonomy.org/json/search/database?items=1000&duplicates=merged"
# result = requests.get(url) # result ist ein requests.models.Response Objekt
# data = result.json() # das Response-Objekt bietet diese nützliche Methode an
# df_bib_pd = pd.DataFrame(data["items"])

#data1 = json.load(open("data/database.json"))
#data2 = json.load(open("data/archive.json"))
#df_search1 = pd.DataFrame(data1["items"])
#df_search2 = pd.DataFrame(data2["items"])
#df = pd.concat([df_search1, df_search2])"""

# data = data.loc[data.type == "Publication"]

In [202]:
url_base = "https://www.bibsonomy.org/json/search/"
url_attr = "?items=1000"

In [204]:
def df_from_query(query):
    url = url_base + query.replace(" ", "%20") + url_attr  
    result = requests.get(url)
    json_data = result.json()
    dataframe = pd.DataFrame(json_data["items"])
    dataframe["query"] = query
    return dataframe

In [206]:
dataframes = []
queries = ["database", "text", "library", "archive"]

for q in queries:
    df = df_from_query(q)
    dataframes.append(df)
    print(f"{len(df)} Ergebnisse für query {q} gefunden.")

2000 Ergebnisse für query database gefunden.
2000 Ergebnisse für query text gefunden.
2000 Ergebnisse für query library gefunden.
2000 Ergebnisse für query archive gefunden.

In [226]:
data = pd.concat(dataframes, ignore_index=True)

In [228]:
data

,type,id,tags,intraHash,label,user,description,date,changeDate,count,...,attachments,categories,url_pdf,data,online,titleaddon,refnum,in-text-citation,w-type,w-projects
0,Bookmark,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, database, desktop, aggregator, daily,...",cc45493bf442b78d923b0b1b9342676b,Office 2.0 Database,springnet,Office 2.0 Database,2006-04-19 19:49:42,2008-06-29 17:52:49,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bookmark,https://www.bibsonomy.org/url/61474ed79d5c3f63...,"[tool, database, 3403, Error, Fix,, recovery,,...",61474ed79d5c3f63c1d0b6dcd8c653f5,SQL Database 3403 Error Fix,traktools,SysTools Software releases an effective SQL da...,2009-09-15 19:13:52,2009-09-15 19:13:52,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bookmark,https://www.bibsonomy.org/url/3cd373dd8ed9c534...,"[Article(s), Design, Database, Information]",3cd373dd8ed9c53483d39eaa928686f6,Database Sharding,panic,"The term ""sharding"" was coined by Google engin...",2011-10-01 02:24:14,2011-10-01 02:27:38,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bookmark,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, 2007, database, socialsoftware, tools...",cc45493bf442b78d923b0b1b9342676b,Office 2.0 Database,akpe,"Overview of roughly 250 Web 2.0 applications, ...",2007-03-14 20:26:50,2011-03-14 16:42:58,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bookmark,https://www.bibsonomy.org/url/2f5f76391c720a9b...,[databases],2f5f76391c720a9b688f60ec6f900f1d,Encyclopedia of Database Systems,ludaesch,Encyclopedia of Database Systems,2007-02-08 11:20:08,2007-09-26 06:23:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,Publication,https://www.bibsonomy.org/bibtex/2040f345d94cd...,[dblp],040f345d94cd5d5e6c4e6a2ca7d2f43e,Faculty self-archiving behavior: Factors affec...,dblp,,2020-06-24 00:00:00,2024-04-10 00:42:34,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7996,Publication,https://www.bibsonomy.org/bibtex/28217f4fe9f6a...,[dblp],8217f4fe9f6a3929c0d365d35447be84,Sensitivity and Access: Unlocking the Colonial...,dblp,,2024-08-08 00:00:00,2024-08-12 07:04:36,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7997,Publication,https://www.bibsonomy.org/bibtex/29994ea45725f...,[dblp],9994ea45725f4b521a1ca2da5f6b1bae,Online hot topic detection from web news archi...,dblp,,2021-09-19 00:00:00,2024-04-10 19:24:49,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7998,Publication,https://www.bibsonomy.org/bibtex/2ee55445bc456...,[dblp],ee55445bc456b80407d888fe2948f6a1,Serge Modular Archive Instrument (SMAI): Bridg...,dblp,,2024-09-16 00:00:00,2024-09-23 07:12:24,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7999,Publication,https://www.bibsonomy.org/bibtex/2dc534ef1b015...,[dblp],dc534ef1b01530bf66755fb1a8eaa51a,The peer-to-peer trace archive: design and com...,dblp,,2024-05-07 00:00:00,2024-05-13 10:00:25,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [230]:
data.columns

Index(['type', 'id', 'tags', 'intraHash', 'label', 'user', 'description',
       'date', 'changeDate', 'count',
       ...
       'attachments', 'categories', 'url_pdf', 'data', 'online', 'titleaddon',
       'refnum', 'in-text-citation', 'w-type', 'w-projects'],
      dtype='object', length=200)

In [232]:
df_filtered = data[['label', 'id', 'type', 'url', 'year', 'author', 'doi', 'query']]

In [234]:
df_filtered = df_filtered.loc[data.type == "Publication"]

In [236]:
df_filtered

,label,id,type,url,year,author,doi,query
1000,EcoliNet: a database of cofunctional gene netw...,https://www.bibsonomy.org/bibtex/2750b8770eec8...,Publication,http://dx.doi.org/10.1093/database/bav001,2015,"[Hanhae Kim, Jung Eun E. Shim, Junha Shin, Ins...",10.1093/database/bav001,database
1001,The drug-minded protein interaction database (...,https://www.bibsonomy.org/bibtex/2d93ac9b6cfa6...,Publication,http://dx.doi.org/10.1093/database/baw041,2016,"[Meik Kunz, Chunguang Liang, Santosh Nilla, Al...",10.1093/database/baw041,database
1002,PhosphoGRID: a database of experimentally veri...,https://www.bibsonomy.org/bibtex/233d3effaf95a...,Publication,http://dx.doi.org/10.1093/database/bap026,2010,"[Chris Stark, Ting-Cheng C. Su, Ashton Breitkr...",10.1093/database/bap026,database
1003,GoSynthetic database tool to analyse natural a...,https://www.bibsonomy.org/bibtex/2ca6461cce248...,Publication,http://dx.doi.org/10.1093/database/bat043,2013,"[C. Liang, B. Kruger, T. Dandekar]",10.1093/database/bat043,database
1004,Database for Mobile Application,https://www.bibsonomy.org/bibtex/2eb1605409b13...,Publication,http://www.ijtsrd.com/computer-science/databas...,2018,[Jasra Nisar Owais Noor Trumboo],NaN,database
...,...,...,...,...,...,...,...,...
7995,Faculty self-archiving behavior: Factors affec...,https://www.bibsonomy.org/bibtex/2040f345d94cd...,Publication,http://dblp.uni-trier.de/db/conf/asist/asist20...,2007,[Jihyun Kim],NaN,archive
7996,Sensitivity and Access: Unlocking the Colonial...,https://www.bibsonomy.org/bibtex/28217f4fe9f6a...,Publication,http://dblp.uni-trier.de/db/journals/dhq/dhq18...,2024,"[Jonathan Dentler, Lise Jaillant, Daniel Folia...",NaN,archive
7997,Online hot topic detection from web news archi...,https://www.bibsonomy.org/bibtex/29994ea45725f...,Publication,http://dblp.uni-trier.de/db/conf/fskd/fskd2014...,2014,"[RuiGuo Yu, Mankun Zhao, Peng Chang, MuWen He]",NaN,archive
7998,Serge Modular Archive Instrument (SMAI): Bridg...,https://www.bibsonomy.org/bibtex/2ee55445bc456...,Publication,http://dblp.uni-trier.de/db/conf/nime/nime2023...,2023,"[Ted Moore, Jean Brazeau]",NaN,archive
7999,The peer-to-peer trace archive: design and com...,https://www.bibsonomy.org/bibtex/2dc534ef1b015...,Publication,http://dblp.uni-trier.de/db/conf/conext/sw2010...,2010,"[Boxun Zhang, Alexandru Iosup, Johan Pouwelse,...",NaN,archive

In [238]:
df_filtered["year"].unique()

array(['2015', '2016', '2010', '2013', '2018', '2005', '2019', '2009',
       '1984', '2011', '2014', '2007', '1990', '2006', '1988', '1986',
       '2017', '2000', '2023', '2004', '1998', '2003', '2008', '2012',
       '2001', '2024', '2021', '2022', '1987', '1999', '2020', '1993',
       '1996', '2002', '1976', '1995', '1980', '1983', '1991', '1994',
       '1997', '1992', '1978', '1985', '1981', '1977', '1989', '1979',
       '{1998}', '1982', '1972', '2006-2012', '19980301', 'o.J.', 'test',
       '1970', '2002 ', ' 2010 ', 'Test-Year', '1931', '1887',
       'August 2007', '1900', '1974', '20-13', 'November 2015', '1946',
       '1973', '2010 ', ' 2000 ', '1975', 'u.å.', '2001ff', '1953',
       '5555', '1938--1957', '1960', '2004/9', '1961', '2001?', '1971',
       '1962', '1957', '1956', '1952', '2009, updated July 2010', '1876',
       '1964', 'Accessed: 20-01-2005', '99', 'November 26th, 2006',
       '1869', 'n.a.', 'n.d.', '1955', '2025', '1898', '1901'],
      dtype=object)

In [240]:
df_filtered["year_correct"] = df_filtered.apply(lambda row: row.year.isdigit(), axis=1)
df_filtered = df_filtered.loc[df_filtered.year_correct == True]

In [242]:
df_filtered["year"].unique()

array(['2015', '2016', '2010', '2013', '2018', '2005', '2019', '2009',
       '1984', '2011', '2014', '2007', '1990', '2006', '1988', '1986',
       '2017', '2000', '2023', '2004', '1998', '2003', '2008', '2012',
       '2001', '2024', '2021', '2022', '1987', '1999', '2020', '1993',
       '1996', '2002', '1976', '1995', '1980', '1983', '1991', '1994',
       '1997', '1992', '1978', '1985', '1981', '1977', '1989', '1979',
       '1982', '1972', '19980301', '1970', '1931', '1887', '1900', '1974',
       '1946', '1973', '1975', '1953', '5555', '1960', '1961', '1971',
       '1962', '1957', '1956', '1952', '1876', '1964', '99', '1869',
       '1955', '2025', '1898', '1901'], dtype=object)

In [246]:
#delete_row = df_filtered.loc[df_filtered['year'] == '5555'].index
#df_filtered.drop(delete_row, inplace=True, axis="index")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_1605/51856490.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.drop(delete_row, inplace=True, axis="index")

In [248]:
df_filtered["year"].unique()

array(['2015', '2016', '2010', '2013', '2018', '2005', '2019', '2009',
       '1984', '2011', '2014', '2007', '1990', '2006', '1988', '1986',
       '2017', '2000', '2023', '2004', '1998', '2003', '2008', '2012',
       '2001', '2024', '2021', '2022', '1987', '1999', '2020', '1993',
       '1996', '2002', '1976', '1995', '1980', '1983', '1991', '1994',
       '1997', '1992', '1978', '1985', '1981', '1977', '1989', '1979',
       '1982', '1972', '1970', '1931', '1887', '1900', '1974', '1946',
       '1973', '1975', '1953', '1960', '1961', '1971', '1962', '1957',
       '1956', '1952', '1876', '1964', '99', '1869', '1955', '2025',
       '1898', '1901'], dtype=object)

In [252]:
df_filtered = df_filtered.loc[df_filtered["author"].isnull() == False]
df_filtered = df_filtered.drop_duplicates(subset = "label", keep ="first")
df_filtered = df_filtered.rename(columns={"label": "title", "author": "authors"})

In [254]:
df_filtered.groupby("year").count().title

year
1869      1
1876      1
1898      1
1900      3
1901      1
       ...
2022    123
2023    109
2024    127
2025      1
99        1
Name: title, Length: 72, dtype: int64

In [258]:
df_filtered = df_filtered.drop("year_correct", axis=1)

In [260]:
df_filtered["editor"] = "Jannik Ott"

In [262]:
df_filtered

,title,id,type,url,year,authors,doi,query,editor
1000,EcoliNet: a database of cofunctional gene netw...,https://www.bibsonomy.org/bibtex/2750b8770eec8...,Publication,http://dx.doi.org/10.1093/database/bav001,2015,"[Hanhae Kim, Jung Eun E. Shim, Junha Shin, Ins...",10.1093/database/bav001,database,Jannik Ott
1001,The drug-minded protein interaction database (...,https://www.bibsonomy.org/bibtex/2d93ac9b6cfa6...,Publication,http://dx.doi.org/10.1093/database/baw041,2016,"[Meik Kunz, Chunguang Liang, Santosh Nilla, Al...",10.1093/database/baw041,database,Jannik Ott
1002,PhosphoGRID: a database of experimentally veri...,https://www.bibsonomy.org/bibtex/233d3effaf95a...,Publication,http://dx.doi.org/10.1093/database/bap026,2010,"[Chris Stark, Ting-Cheng C. Su, Ashton Breitkr...",10.1093/database/bap026,database,Jannik Ott
1003,GoSynthetic database tool to analyse natural a...,https://www.bibsonomy.org/bibtex/2ca6461cce248...,Publication,http://dx.doi.org/10.1093/database/bat043,2013,"[C. Liang, B. Kruger, T. Dandekar]",10.1093/database/bat043,database,Jannik Ott
1004,Database for Mobile Application,https://www.bibsonomy.org/bibtex/2eb1605409b13...,Publication,http://www.ijtsrd.com/computer-science/databas...,2018,[Jasra Nisar Owais Noor Trumboo],NaN,database,Jannik Ott
...,...,...,...,...,...,...,...,...,...
7995,Faculty self-archiving behavior: Factors affec...,https://www.bibsonomy.org/bibtex/2040f345d94cd...,Publication,http://dblp.uni-trier.de/db/conf/asist/asist20...,2007,[Jihyun Kim],NaN,archive,Jannik Ott
7996,Sensitivity and Access: Unlocking the Colonial...,https://www.bibsonomy.org/bibtex/28217f4fe9f6a...,Publication,http://dblp.uni-trier.de/db/journals/dhq/dhq18...,2024,"[Jonathan Dentler, Lise Jaillant, Daniel Folia...",NaN,archive,Jannik Ott
7997,Online hot topic detection from web news archi...,https://www.bibsonomy.org/bibtex/29994ea45725f...,Publication,http://dblp.uni-trier.de/db/conf/fskd/fskd2014...,2014,"[RuiGuo Yu, Mankun Zhao, Peng Chang, MuWen He]",NaN,archive,Jannik Ott
7998,Serge Modular Archive Instrument (SMAI): Bridg...,https://www.bibsonomy.org/bibtex/2ee55445bc456...,Publication,http://dblp.uni-trier.de/db/conf/nime/nime2023...,2023,"[Ted Moore, Jean Brazeau]",NaN,archive,Jannik Ott
7999,The peer-to-peer trace archive: design and com...,https://www.bibsonomy.org/bibtex/2dc534ef1b015...,Publication,http://dblp.uni-trier.de/db/conf/conext/sw2010...,2010,"[Boxun Zhang, Alexandru Iosup, Johan Pouwelse,...",NaN,archive,Jannik Ott

In [264]:
df_filtered.to_json("data/output.json", orient="records")

In [266]:
# check, if it looks correct
with open("data/output.json", "r") as f:
    j_load = json.load(f)
    print(json.dumps(j_load, indent=2))

[
  {
    "title": "EcoliNet: a database of cofunctional gene network for Escherichia coli.",
    "id": "https://www.bibsonomy.org/bibtex/2750b8770eec83ca7d18107df3d520113/karthikraman",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/database/bav001",
    "year": "2015",
    "authors": [
      "Hanhae Kim",
      "Jung Eun E. Shim",
      "Junha Shin",
      "Insuk Lee"
    ],
    "doi": "10.1093/database/bav001",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "The drug-minded protein interaction database (DrumPID) for efficient target analysis and drug development.",
    "id": "https://www.bibsonomy.org/bibtex/2d93ac9b6cfa60505ee7b3d7ffefca15f/karthikraman",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/database/baw041",
    "year": "2016",
    "authors": [
      "Meik Kunz",
      "Chunguang Liang",
      "Santosh Nilla",
      "Alexander Cecil",
      "Thomas Dandekar"
    ],
    "doi": "10.1093/database/baw041",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "PhosphoGRID: a database of experimentally verified in vivo protein phosphorylation sites from the budding yeast Saccharomyces cerevisiae.",
    "id": "https://www.bibsonomy.org/bibtex/233d3effaf95a6d714a6fb06099bdf647/karthikraman",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/database/bap026",
    "year": "2010",
    "authors": [
      "Chris Stark",
      "Ting-Cheng C. Su",
      "Ashton Breitkreutz",
      "Pedro Lourenco",
      "Matthew Dahabieh",
      "Bobby-Joe J. Breitkreutz",
      "Mike Tyers",
      "Ivan Sadowski"
    ],
    "doi": "10.1093/database/bap026",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "GoSynthetic database tool to analyse natural and engineered molecular processes",
    "id": "https://www.bibsonomy.org/bibtex/2ca6461cce248858567237c85cca8f378/evp66rk",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/database/bat043",
    "year": "2013",
    "authors": [
      "C. Liang",
      "B. Kruger",
      "T. Dandekar"
    ],
    "doi": "10.1093/database/bat043",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Database for Mobile Application",
    "id": "https://www.bibsonomy.org/bibtex/2eb1605409b134cc14adb1c45bc1bd3b0/ijtsrd",
    "type": "Publication",
    "url": "http://www.ijtsrd.com/computer-science/database/11215/database-for-mobile-application/jasra-nisar",
    "year": "2018",
    "authors": [
      "Jasra Nisar Owais Noor Trumboo"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "An international otology database",
    "id": "https://www.bibsonomy.org/bibtex/25f85238089c4a2ec183b243bf83fa523/stevenarild",
    "type": "Publication",
    "url": "http://www.ncbi.nlm.nih.gov.ep.fjernadgang.kb.dk/pubmed/?term=yung+gjuric+haeusler",
    "year": "2005",
    "authors": [
      "M Yung",
      "M Gjuric",
      "R Haeusler",
      "P H Van de Heyning",
      "C Martin",
      "I R Swan",
      "R A Tange",
      "P T Huy",
      " European Otology Database Project Group"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Enable Auditing in Oracle database",
    "id": "https://www.bibsonomy.org/bibtex/27757584ce817952545d28d956896ba6a/ijtsrd",
    "type": "Publication",
    "url": "https://www.ijtsrd.com/computer-science/database/29881/enable-auditing-in-oracle-database/amrish-srivastava",
    "year": "2019",
    "authors": [
      "Amrish Srivastava"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Database and database application security",
    "id": "https://www.bibsonomy.org/bibtex/2b8151c596a8d3eb7e7233f1a47d53b08/malte.wunsch",
    "type": "Publication",
    "url": "http://portal.acm.org/citation.cfm?id=1562877.1562909",
    "year": "2009",
    "authors": [
      "Huwida E. Said",
      "Mario A. Guimaraes",
      "Zakaria Maamar",
      "Leon Jololian"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Vertical partitioning algorithms for database design",
    "id": "https://www.bibsonomy.org/bibtex/281eb5e7b67cc969365c65a67721cb495/joergh",
    "type": "Publication",
    "url": "http://portal.acm.org/citation.cfm?id=1994.2209",
    "year": "1984",
    "authors": [
      "Shamkant Navathe",
      "Stefano Ceri",
      "Gio Wiederhold",
      "Jinglie Dou"
    ],
    "doi": "http://doi.acm.org/10.1145/1994.2209",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "The Reactome BioMart.",
    "id": "https://www.bibsonomy.org/bibtex/206ba5aaa99967712038c684d1864c421/karthikraman",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/database/bar031",
    "year": "2011",
    "authors": [
      "Robin A. Haw",
      "David Croft",
      "Christina K. Yung",
      "Nelson Ndegwa",
      "Peter D'Eustachio",
      "Henning Hermjakob",
      "Lincoln D. Stein"
    ],
    "doi": "10.1093/database/bar031",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "WholeCellSimDB: a hybrid relational/HDF database for whole-cell model predictions.",
    "id": "https://www.bibsonomy.org/bibtex/235a7f0439923ab61281f80bb4fbe77c9/karthikraman",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/database/bau095",
    "year": "2014",
    "authors": [
      "Jonathan R. Karr",
      "Nolan C. Phillips",
      "Markus W. Covert"
    ],
    "doi": "10.1093/database/bau095",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Oracle Database Backup Testing",
    "id": "https://www.bibsonomy.org/bibtex/23300b9d02e6150493d24278d652fd980/ijtsrd",
    "type": "Publication",
    "url": "http://www.ijtsrd.com/computer-science/database/11572/oracle-database-backup-testing/vijay-kumar-tiwari",
    "year": "2018",
    "authors": [
      "Vijay Kumar Tiwari"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Implications of certain assumptions in database performance evauation",
    "id": "https://www.bibsonomy.org/bibtex/2a8e950024e05fb6206578bb5a3c4d44a/jhammerb",
    "type": "Publication",
    "url": "http://portal.acm.org/citation.cfm?doid=329.318578",
    "year": "1984",
    "authors": [
      "S. Christodoulakis"
    ],
    "doi": "http://doi.acm.org/10.1145/329.318578",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "A standardized database management of middle ear surgery in Korea",
    "id": "https://www.bibsonomy.org/bibtex/24d001da0c68be5efe71702f9ecc2e4f2/stevenarild",
    "type": "Publication",
    "url": "http://www.ncbi.nlm.nih.gov.ep.fjernadgang.kb.dk/pubmed/?term=kim+hj+a+standardized+database+management",
    "year": "2007",
    "authors": [
      "H J Kim"
    ],
    "doi": "10.1080/03655230701624871",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "SwissRegulon, a database of genome-wide annotations of regulatory sites: recent updates",
    "id": "https://www.bibsonomy.org/bibtex/2e15360b1fc6345c1913a65b3112680fd/karthikraman",
    "type": "Publication",
    "url": "https://www.ncbi.nlm.nih.gov/pubmed/?term=SwissRegulon%2C+a+database+of+genome-wide+annotations+of+regulatory+sites%3A+recent+updates",
    "year": "2013",
    "authors": [
      "M Pachkov",
      "P J Balwierz",
      "P Arnold",
      "E Ozonov",
      "E van Nimwegen"
    ],
    "doi": "10.1093/nar/gks1145",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "ConsensusPathDB--a database for integrating human functional interaction networks",
    "id": "https://www.bibsonomy.org/bibtex/22b7406cd1753f56e5a06ae8b48b24cdf/wnpxrz",
    "type": "Publication",
    "url": "http://www.ncbi.nlm.nih.gov/pubmed/18940869",
    "year": "2009",
    "authors": [
      "A Kamburov",
      "C Wierling",
      "H Lehrach",
      "R Herwig"
    ],
    "doi": "10.1093/nar/gkn698",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "PID: the Pathway Interaction Database",
    "id": "https://www.bibsonomy.org/bibtex/250055d426be1ad08439d9523ae3c83d1/wnpxrz",
    "type": "Publication",
    "url": "http://www.ncbi.nlm.nih.gov/pubmed/18832364",
    "year": "2009",
    "authors": [
      "C F Schaefer",
      "K Anthony",
      "S Krupa",
      "J Buchoff",
      "M Day",
      "T Hannay",
      "K H Buetow"
    ],
    "doi": "10.1093/nar/gkn653",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Parallel database systems: the future of database processing or a passing fad?",
    "id": "https://www.bibsonomy.org/bibtex/28af31bbdb0bde12ef6965492973f4831/jhammerb",
    "type": "Publication",
    "url": "http://portal.acm.org/citation.cfm?id=122058.122071",
    "year": "1990",
    "authors": [
      "David J. DeWitt",
      "Jim Gray"
    ],
    "doi": "http://doi.acm.org/10.1145/122058.122071",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "The HUGO Gene Nomenclature Database, 2006 updates",
    "id": "https://www.bibsonomy.org/bibtex/29b3aa72d312bf8a3e038ca92b6612fcd/sbsad",
    "type": "Publication",
    "url": "http://www.ncbi.nlm.nih.gov/pubmed/16381876",
    "year": "2006",
    "authors": [
      "T A Eyre",
      "F Ducluzeau",
      "T P Sneddon",
      "S Povey",
      "E A Bruford",
      "M J Lush"
    ],
    "doi": "10.1093/nar/gkj147",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Traditional Databases vs NOSQL",
    "id": "https://www.bibsonomy.org/bibtex/2a25665734dddc3bd249a981cd424fc74/ijtsrd",
    "type": "Publication",
    "url": "http://www.ijtsrd.com/computer-science/database/12961/traditional-databases-vs-nosql/owais-noor-trumboo",
    "year": "2018",
    "authors": [
      "Owais Noor Trumboo Jasra Nisar"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Federated database systems for managing distributed, heterogeneous, and autonomous databases",
    "id": "https://www.bibsonomy.org/bibtex/2d8ab08ff39573bd64e7dc080adb2230b/buehner",
    "type": "Publication",
    "url": "http://delivery.acm.org/10.1145/100000/96604/p183-sheth.pdf?key1=96604&key2=8693487821&coll=GUIDE&dl=ACM&CFID=107002774&CFTOKEN=13258373",
    "year": "1990",
    "authors": [
      "Amit P. Sheth",
      "James A. Larson"
    ],
    "doi": "10.1145/96602.96604",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Migration from relational database like MySQL to nosql database like Cassandra is necessary and how to migrate it using spark",
    "id": "https://www.bibsonomy.org/bibtex/2c47aa8b0c0695dbf04c04e34bb3a9101/ijtsrd",
    "type": "Publication",
    "url": "http://www.ijtsrd.com/engineering/computer-engineering/57/migration-from-relational-database-like-mysql-to-nosql-database-like-cassandra-is-necessary-and-how-to-migrate-it-using-spark/dr-kishor-atkotiya",
    "year": "2016",
    "authors": [
      "Dr. Kishor Atkotiya | Parag Shukla"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Database Security Model using Access Control Mechanism in Student Data Management",
    "id": "https://www.bibsonomy.org/bibtex/2f21be0dc285cb90890e1d9ce3146a63a/ijtsrd",
    "type": "Publication",
    "url": "https://www.ijtsrd.com/computer-science/database/22820/database-security-model-using-access-control-mechanism-in-student-data-management/aye-mon-win",
    "year": "2019",
    "authors": [
      "Aye Mon Win | Khin Lay Myint"
    ],
    "doi": "https://doi.org/10.31142/ijtsrd22820",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Survival of an Intrusion Tolerance Database System",
    "id": "https://www.bibsonomy.org/bibtex/24f8b60cb12c7f1d1b31465d7e7b2f44b/ijtsrd",
    "type": "Publication",
    "url": "https://www.ijtsrd.com/computer-science/computer-security/26748/survival-of-an-intrusion-tolerance-database-system/su-thawda-win",
    "year": "2019",
    "authors": [
      "Su Thawda Win"
    ],
    "doi": "https://doi.org/10.31142/ijtsrd26748",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "BioNumbers--the database of key numbers in molecular and cell biology",
    "id": "https://www.bibsonomy.org/bibtex/2c35febbc664422e27257b6f2f27b40f4/karthikraman",
    "type": "Publication",
    "url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2808940/",
    "year": "2010",
    "authors": [
      "R Milo",
      "P Jorgensen",
      "U Moran",
      "G Weber",
      "M Springer"
    ],
    "doi": "10.1093/nar/gkp889",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Janaushadhi Database Management System",
    "id": "https://www.bibsonomy.org/bibtex/20900193932683227409336a3befeac54/ijtsrd",
    "type": "Publication",
    "url": "https://www.ijtsrd.com/computer-science/database/26403/janaushadhi-database-management-system/naimisha-u",
    "year": "2019",
    "authors": [
      "Naimisha U | Ashritha A"
    ],
    "doi": "https://doi.org/10.31142/ijtsrd26403",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "GAMMA\\\u2014a high performance dataflow database machine",
    "id": "https://www.bibsonomy.org/bibtex/2a295018d8ecc0212aca487ae1b0c753e/jhammerb",
    "type": "Publication",
    "url": "http://portal.acm.org/citation.cfm?id=48751.48773",
    "year": "1988",
    "authors": [
      "David J. DeWitt",
      "Goetz Graefe",
      "Krishna B. Kumar",
      "Robert H. Gerber",
      "Michael L. Heytens",
      "M. Muralikrishna"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Performance Driven Database Design for Scalable Web Applications",
    "id": "https://www.bibsonomy.org/bibtex/2c753bff717eb9632d39e3679f7c269ef/mbruschi",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1007/978-3-642-03973-7_5",
    "year": "2009",
    "authors": [
      "Jozsef Patvarczki",
      "Murali Mani",
      "Neil Heffernan"
    ],
    "doi": "10.1007/978-3-642-03973-7_5",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "A comparative analysis of methodologies for database schema integration",
    "id": "https://www.bibsonomy.org/bibtex/22636802d129dbf10d3dc35bdfdc6efb6/gravity",
    "type": "Publication",
    "url": "http://portal.acm.org/citation.cfm?doid=27633.27634",
    "year": "1986",
    "authors": [
      "C. Batini",
      "M. Lenzerini",
      "S. B. Navathe"
    ],
    "doi": "http://doi.acm.org/10.1145/27633.27634",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "A Comparison between Relational Databases and NoSQL Databases",
    "id": "https://www.bibsonomy.org/bibtex/292e537486422445d574ddbbef9a49300/ijtsrd",
    "type": "Publication",
    "url": "http://www.ijtsrd.com/computer-science/database/11214/a-comparison-between-relational-databases-and-nosql-databases/behjat-u-nisa",
    "year": "2018",
    "authors": [
      "Behjat U Nisa"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "XML and relational database management systems: the inside story",
    "id": "https://www.bibsonomy.org/bibtex/26d3b73cfb1b666af1155c893cd37f5d5/malte.wunsch",
    "type": "Publication",
    "url": "http://portal.acm.org/citation.cfm?id=1066157.1066298",
    "year": "2005",
    "authors": [
      "Michael Rys",
      "Don Chamberlin",
      "Daniela Florescu"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "The Claremont report on database research",
    "id": "https://www.bibsonomy.org/bibtex/2c23ca6a7338e9687327054b7d62596bf/sb3000",
    "type": "Publication",
    "url": "http://doi.acm.org/10.1145/1516046.1516062",
    "year": "2009",
    "authors": [
      "Rakesh Agrawal",
      "Anastasia Ailamaki",
      "Philip A. Bernstein",
      "Eric A. Brewer",
      "Michael J. Carey",
      "Surajit Chaudhuri",
      "Anhai Doan",
      "Daniela Florescu",
      "Michael J. Franklin",
      "Hector Garcia-Molina",
      "Johannes Gehrke",
      "Le Gruenwald",
      "Laura M. Haas",
      "Alon Y. Halevy",
      "Joseph M. Hellerstein",
      "Yannis E. Ioannidis",
      "Hank F. Korth",
      "Donald Kossmann",
      "Samuel Madden",
      "Roger Magoulas",
      "Beng Chin Ooi",
      "Tim O'Reilly",
      "Raghu Ramakrishnan",
      "Sunita Sarawagi",
      "Michael Stonebraker",
      "Alexander S. Szalay",
      "Gerhard Weikum"
    ],
    "doi": "10.1145/1516046.1516062",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Argonaute--a database for gene regulation by mammalian microRNAs.",
    "id": "https://www.bibsonomy.org/bibtex/2ebee7ffeb63027567b55bf06c3d56e87/bbrors",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/nar/gkj093",
    "year": "2006",
    "authors": [
      "Priyanka Shahi",
      "Serguei Loukianiouk",
      "Andreas Bohne-Lang",
      "Marc Kenzelmann",
      "Stefan K\u00fcffer",
      "Sabine Maertens",
      "Roland Eils",
      "Herrmann-Josef Gr\u00f6ne",
      "Norbert Gretz",
      "Benedikt Brors"
    ],
    "doi": "10.1093/nar/gkj093",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "Meta-Modeling to design the Structured Database Schema",
    "id": "https://www.bibsonomy.org/bibtex/21ff8657202cd17730f4dfb25f867073d/dm.kovalev",
    "type": "Publication",
    "url": "",
    "year": "2006",
    "authors": [
      "Elvira Locuratolo"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "SMPDB: The Small Molecule Pathway Database.",
    "id": "https://www.bibsonomy.org/bibtex/28679729b73db4e8c758f177ed6c1b7bb/karthikraman",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/nar/gkp1002",
    "year": "2010",
    "authors": [
      "Alex Frolkis",
      "Craig Knox",
      "Emilia Lim",
      "Timothy Jewison",
      "Vivian Law",
      "David D. Hau",
      "Phillip Liu",
      "Bijaya Gautam",
      "Son Ly",
      "An Chi C. Guo",
      "Jianguo Xia",
      "Yongjie Liang",
      "Savita Shrivastava",
      "David S. Wishart"
    ],
    "doi": "10.1093/nar/gkp1002",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "RAIN: RNA-protein Association and Interaction Networks.",
    "id": "https://www.bibsonomy.org/bibtex/2d13ac84ab45538ea9d0463e006d70ffa/karthikraman",
    "type": "Publication",
    "url": "http://dx.doi.org/10.1093/database/baw167",
    "year": "2017",
    "authors": [
      "Alexander Junge",
      "Jan C. Refsgaard",
      "Christian Garde",
      "Xiaoyong Pan",
      "Alberto Santos",
      "Ferhat Alkan",
      "Christian Anthon",
      "Christian von Mering",
      "Christopher T. Workman",
      "Lars Juhl J. Jensen",
      "Jan Gorodkin"
    ],
    "doi": "10.1093/database/baw167",
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "LIGAND: chemical database of enzyme reactions",
    "id": "https://www.bibsonomy.org/bibtex/263a5437227eab1cc867c5cf5e310779e/artheibault",
    "type": "Publication",
    "url": "http://dblp.uni-trier.de/db/journals/nar/nar28.html#GotoNK00",
    "year": "2000",
    "authors": [
      "Susumu Goto",
      "Takaaki Nishioka",
      "Minoru Kanehisa"
    ],
    "doi": null,
    "query": "database",
    "editor": "Jannik Ott"
  },
  {
    "title": "ChEBI - Chemical Entities of Biological Interest",
    "id": "https://www.bibsonomy.org/bibtex/232c444add4e2b89c8e61b6406211eb0f/fairybasslet",
    "type": "Publication",
    "url": "http://www.oxfordjournals.org/nar/database/summary/646",
    "year": "2006",
    "authors": [
      "P. de Matos",
      "M. Ennis",
      "M. Zbinden",
      "A. McNaught",
      "R. Alc\u00e1ntara",
      "M. Darsow",
      "M. Guedj",
      "M. Ashburner",