# Aufgabe Modul 2

In [97]:
import pandas as pd
import requests
import json

In [99]:
# url = "https://www.bibsonomy.org/json/search/database?items=1000&duplicates=merged"
# result = requests.get(url) # result ist ein requests.models.Response Objekt
# data = result.json() # das Response-Objekt bietet diese nützliche Methode an
# df_bib_pd = pd.DataFrame(data["items"])

In [101]:
data1 = json.load(open("data/database.json"))
data2 = json.load(open("data/archive.json"))
df_search1 = pd.DataFrame(data1["items"])
df_search2 = pd.DataFrame(data2["items"])
df = pd.concat([df_search1, df_search2])

In [103]:
df

,type,id,tags,intraHash,label,user,description,date,changeDate,count,...,data,online,dnbtitleid,titleaddon,refnum,in-text-citation,w-type,w-projects,review,oai
0,Bookmark,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, database, desktop, aggregator, daily,...",cc45493bf442b78d923b0b1b9342676b,Office 2.0 Database,springnet,Office 2.0 Database,2006-04-19 19:49:42,2008-06-29 17:52:49,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bookmark,https://www.bibsonomy.org/url/61474ed79d5c3f63...,"[tool, database, 3403, Error, Fix,, recovery,,...",61474ed79d5c3f63c1d0b6dcd8c653f5,SQL Database 3403 Error Fix,traktools,SysTools Software releases an effective SQL da...,2009-09-15 19:13:52,2009-09-15 19:13:52,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bookmark,https://www.bibsonomy.org/url/3cd373dd8ed9c534...,"[Article(s), Design, Database, Information]",3cd373dd8ed9c53483d39eaa928686f6,Database Sharding,panic,"The term ""sharding"" was coined by Google engin...",2011-10-01 02:24:14,2011-10-01 02:27:38,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bookmark,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, 2007, database, socialsoftware, tools...",cc45493bf442b78d923b0b1b9342676b,Office 2.0 Database,akpe,"Overview of roughly 250 Web 2.0 applications, ...",2007-03-14 20:26:50,2011-03-14 16:42:58,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bookmark,https://www.bibsonomy.org/url/2f5f76391c720a9b...,[databases],2f5f76391c720a9b688f60ec6f900f1d,Encyclopedia of Database Systems,ludaesch,Encyclopedia of Database Systems,2007-02-08 11:20:08,2007-09-26 06:23:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Publication,https://www.bibsonomy.org/bibtex/24d1d395f96e5...,[dblp],4d1d395f96e5085554c516c5666c3ccf,Design Issues for a Digital x-Ray Archive Acce...,dblp,,2024-10-06 00:00:00,2024-10-07 08:49:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,Publication,https://www.bibsonomy.org/bibtex/2c39dd3220ad9...,[dblp],c39dd3220ad927cf40ddd2f2dc15afe0,"ADSM: A Multi-Platform, Scalable, Backup and A...",dblp,,2023-03-23 00:00:00,2024-04-10 19:39:00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,Publication,https://www.bibsonomy.org/bibtex/2a63bd364207f...,[dblp],a63bd364207fd1d836435d79076b6bb3,An Elite Archive-Assisted Multi-Objective Evol...,dblp,,2024-08-20 00:00:00,2024-08-26 07:26:33,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,Publication,https://www.bibsonomy.org/bibtex/20e09c3c0700c...,[dblp],0e09c3c0700cff326299926cd28b3298,A Vendor Neutral Archive with MONAI for Automa...,dblp,,2024-08-19 00:00:00,2024-08-26 08:00:23,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,Publication,https://www.bibsonomy.org/bibtex/2e05a4feee791...,[dblp],e05a4feee7914c86bef22e88acd9cde4,The Image and Data Archive at the Laboratory o...,dblp,,2024-10-06 00:00:00,2024-10-07 07:12:01,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Filtern Sie die Daten so, dass nur noch Einträge des Typs "Publication" enthalten sind.

In [106]:
df = df.loc[df.type == "Publication"]

Überlegen Sie, welche Felder Sie möglicherweise umbenennen wollen, und welche Sie nicht benötigen. Benennen Sie entsprechend Spalten um und wählen Sie nur die Spalten, die für Sie sinnvolle Informationen enthalten. Mögliche Änderungen der Daten sind das Umbenennen zu eindeutigeren Bezeichnungen (wie beispielsweise im Pandas Tutorial "label" zu "title"). Filtern Sie ihre Daten jedoch nicht zu drastisch und entfernen Sie nicht zu viele Felder, damit im zweiten Modulteil noch genügend Informationen übrig bleiben.

In [109]:
df_selection = df[["label", "author", "year", "type", "count"]]

In [111]:
df_selection = df_selection.loc[df_selection["author"].isnull() == False]
df_selection = df_selection.drop_duplicates(subset = "label", keep ="first")
df_selection = df_selection.rename(columns={"label": "title", "author": "authors"})

In [113]:
df_selection

,title,authors,year,type,count
1000,EcoliNet: a database of cofunctional gene netw...,"[Hanhae Kim, Jung Eun E. Shim, Junha Shin, Ins...",2015,Publication,1
1001,The drug-minded protein interaction database (...,"[Meik Kunz, Chunguang Liang, Santosh Nilla, Al...",2016,Publication,10
1002,PhosphoGRID: a database of experimentally veri...,"[Chris Stark, Ting-Cheng C. Su, Ashton Breitkr...",2010,Publication,1
1003,GoSynthetic database tool to analyse natural a...,"[C. Liang, B. Kruger, T. Dandekar]",2013,Publication,6
1004,Database for Mobile Application,[Jasra Nisar Owais Noor Trumboo],2018,Publication,1
...,...,...,...,...,...
1995,Design Issues for a Digital x-Ray Archive Acce...,"[George R. Thoma, L. Rodney Long, Lewis E. Ber...",1994,Publication,1
1996,"ADSM: A Multi-Platform, Scalable, Backup and A...","[Luis-Felipe Cabrera, Robert M. Rees, Stefan S...",1995,Publication,1
1997,An Elite Archive-Assisted Multi-Objective Evol...,"[Wenjing Hong, Cheng Chen, Zexuan Zhu, Ke Tang]",2024,Publication,1
1998,A Vendor Neutral Archive with MONAI for Automa...,"[Rui Jesus, José Frías, Luís Bastião Silva, Ca...",2023,Publication,1
1999,The Image and Data Archive at the Laboratory o...,"[Karen L. Crawford, Scott C. Neu, Arthur W. Toga]",2016,Publication,1

In [115]:
df_selection["year"].unique()

array(['2015', '2016', '2010', '2013', '2018', '2005', '2019', '2009',
       '1984', '2011', '2014', '2007', '1990', '2006', '1988', '1986',
       '2017', '2000', '2023', '2004', '1998', '2003', '2008', '2012',
       '2001', '2024', '2021', '2022', '1987', '1999', '1993', '1996',
       '2002', '1976', '1995', '2020', '1980', '1983', '1991', '1994',
       '1997', '1992', '1978', '1985', '1981', '1977', '1989', '1979',
       '{1998}', '1982', '1972', '2006-2012', '19980301', '1964', '1973',
       'Accessed: 20-01-2005', 'November 26th, 2006', '1869', 'n.a.',
       'n.d.', '1900', '1955', '1898', '1901'], dtype=object)

In [117]:
df_selection["year_correct"] = df_selection.apply(lambda row: row.year.isdigit(), axis=1)

In [119]:
df_selection = df_selection.loc[df_selection.year_correct == True]

In [121]:
df_selection["year"].unique()

array(['2015', '2016', '2010', '2013', '2018', '2005', '2019', '2009',
       '1984', '2011', '2014', '2007', '1990', '2006', '1988', '1986',
       '2017', '2000', '2023', '2004', '1998', '2003', '2008', '2012',
       '2001', '2024', '2021', '2022', '1987', '1999', '1993', '1996',
       '2002', '1976', '1995', '2020', '1980', '1983', '1991', '1994',
       '1997', '1992', '1978', '1985', '1981', '1977', '1989', '1979',
       '1982', '1972', '19980301', '1964', '1973', '1869', '1900', '1955',
       '1898', '1901'], dtype=object)

In [153]:
delete_row = df_selection.loc[df_selection['year'] == '19980301'].index
#df_selection.drop(delete_row, inplace=True, axis="index")

Index([], dtype='int64')

In [155]:
df_selection["year"].unique()

array(['2015', '2016', '2010', '2013', '2018', '2005', '2019', '2009',
       '1984', '2011', '2014', '2007', '1990', '2006', '1988', '1986',
       '2017', '2000', '2023', '2004', '1998', '2003', '2008', '2012',
       '2001', '2024', '2021', '2022', '1987', '1999', '1993', '1996',
       '2002', '1976', '1995', '2020', '1980', '1983', '1991', '1994',
       '1997', '1992', '1978', '1985', '1981', '1977', '1989', '1979',
       '1982', '1972', '1964', '1973', '1869', '1900', '1955', '1898',
       '1901'], dtype=object)

In [186]:
df_selection_dropped.groupby("year").count().title

year
1869      1
1898      1
1900      2
1901      1
1955      1
1964      1
1972      1
1973      2
1976      3
1977      4
1978      3
1979      3
1980      5
1981      4
1982      3
1983      5
1984     11
1985      4
1986     10
1987      7
1988      5
1989      3
1990     12
1991     17
1992     25
1993     20
1994     12
1995     24
1996     14
1997     23
1998     18
1999     19
2000     33
2001     30
2002     45
2003     50
2004     65
2005     75
2006     84
2007     63
2008     50
2009     74
2010     80
2011     63
2012     80
2013     75
2014     54
2015     58
2016     65
2017     55
2018     78
2019     63
2020     39
2021     48
2022     71
2023     68
2024    114
Name: title, dtype: int64

In [159]:
df_selection_dropped = df_selection.drop("year_correct", axis=1)

In [169]:
df_selection_dropped["editor"] = "Jannik Ott"

Export als JSON

In [176]:
df_selection_dropped.to_json("data/output.json", orient="records")

In [178]:
# check, if it looks correct
with open("data/output.json", "r") as f:
    j_load = json.load(f)
    print(json.dumps(j_load, indent=2))

[
  {
    "title": "EcoliNet: a database of cofunctional gene network for Escherichia coli.",
    "authors": [
      "Hanhae Kim",
      "Jung Eun E. Shim",
      "Junha Shin",
      "Insuk Lee"
    ],
    "year": "2015",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "The drug-minded protein interaction database (DrumPID) for efficient target analysis and drug development.",
    "authors": [
      "Meik Kunz",
      "Chunguang Liang",
      "Santosh Nilla",
      "Alexander Cecil",
      "Thomas Dandekar"
    ],
    "year": "2016",
    "type": "Publication",
    "count": 10,
    "editor": "Jannik Ott"
  },
  {
    "title": "PhosphoGRID: a database of experimentally verified in vivo protein phosphorylation sites from the budding yeast Saccharomyces cerevisiae.",
    "authors": [
      "Chris Stark",
      "Ting-Cheng C. Su",
      "Ashton Breitkreutz",
      "Pedro Lourenco",
      "Matthew Dahabieh",
      "Bobby-Joe J. Breitkreutz",
      "Mike Tyers",
      "Ivan Sadowski"
    ],
    "year": "2010",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "GoSynthetic database tool to analyse natural and engineered molecular processes",
    "authors": [
      "C. Liang",
      "B. Kruger",
      "T. Dandekar"
    ],
    "year": "2013",
    "type": "Publication",
    "count": 6,
    "editor": "Jannik Ott"
  },
  {
    "title": "Database for Mobile Application",
    "authors": [
      "Jasra Nisar Owais Noor Trumboo"
    ],
    "year": "2018",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "An international otology database",
    "authors": [
      "M Yung",
      "M Gjuric",
      "R Haeusler",
      "P H Van de Heyning",
      "C Martin",
      "I R Swan",
      "R A Tange",
      "P T Huy",
      " European Otology Database Project Group"
    ],
    "year": "2005",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Enable Auditing in Oracle database",
    "authors": [
      "Amrish Srivastava"
    ],
    "year": "2019",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Database and database application security",
    "authors": [
      "Huwida E. Said",
      "Mario A. Guimaraes",
      "Zakaria Maamar",
      "Leon Jololian"
    ],
    "year": "2009",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Vertical partitioning algorithms for database design",
    "authors": [
      "Shamkant Navathe",
      "Stefano Ceri",
      "Gio Wiederhold",
      "Jinglie Dou"
    ],
    "year": "1984",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "The Reactome BioMart.",
    "authors": [
      "Robin A. Haw",
      "David Croft",
      "Christina K. Yung",
      "Nelson Ndegwa",
      "Peter D'Eustachio",
      "Henning Hermjakob",
      "Lincoln D. Stein"
    ],
    "year": "2011",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "WholeCellSimDB: a hybrid relational/HDF database for whole-cell model predictions.",
    "authors": [
      "Jonathan R. Karr",
      "Nolan C. Phillips",
      "Markus W. Covert"
    ],
    "year": "2014",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Oracle Database Backup Testing",
    "authors": [
      "Vijay Kumar Tiwari"
    ],
    "year": "2018",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Implications of certain assumptions in database performance evauation",
    "authors": [
      "S. Christodoulakis"
    ],
    "year": "1984",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "A standardized database management of middle ear surgery in Korea",
    "authors": [
      "H J Kim"
    ],
    "year": "2007",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "SwissRegulon, a database of genome-wide annotations of regulatory sites: recent updates",
    "authors": [
      "M Pachkov",
      "P J Balwierz",
      "P Arnold",
      "E Ozonov",
      "E van Nimwegen"
    ],
    "year": "2013",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "ConsensusPathDB--a database for integrating human functional interaction networks",
    "authors": [
      "A Kamburov",
      "C Wierling",
      "H Lehrach",
      "R Herwig"
    ],
    "year": "2009",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "PID: the Pathway Interaction Database",
    "authors": [
      "C F Schaefer",
      "K Anthony",
      "S Krupa",
      "J Buchoff",
      "M Day",
      "T Hannay",
      "K H Buetow"
    ],
    "year": "2009",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "Parallel database systems: the future of database processing or a passing fad?",
    "authors": [
      "David J. DeWitt",
      "Jim Gray"
    ],
    "year": "1990",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "The HUGO Gene Nomenclature Database, 2006 updates",
    "authors": [
      "T A Eyre",
      "F Ducluzeau",
      "T P Sneddon",
      "S Povey",
      "E A Bruford",
      "M J Lush"
    ],
    "year": "2006",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Traditional Databases vs NOSQL",
    "authors": [
      "Owais Noor Trumboo Jasra Nisar"
    ],
    "year": "2018",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Federated database systems for managing distributed, heterogeneous, and autonomous databases",
    "authors": [
      "Amit P. Sheth",
      "James A. Larson"
    ],
    "year": "1990",
    "type": "Publication",
    "count": 5,
    "editor": "Jannik Ott"
  },
  {
    "title": "Migration from relational database like MySQL to nosql database like Cassandra is necessary and how to migrate it using spark",
    "authors": [
      "Dr. Kishor Atkotiya | Parag Shukla"
    ],
    "year": "2016",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Database Security Model using Access Control Mechanism in Student Data Management",
    "authors": [
      "Aye Mon Win | Khin Lay Myint"
    ],
    "year": "2019",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Survival of an Intrusion Tolerance Database System",
    "authors": [
      "Su Thawda Win"
    ],
    "year": "2019",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "BioNumbers--the database of key numbers in molecular and cell biology",
    "authors": [
      "R Milo",
      "P Jorgensen",
      "U Moran",
      "G Weber",
      "M Springer"
    ],
    "year": "2010",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Janaushadhi Database Management System",
    "authors": [
      "Naimisha U | Ashritha A"
    ],
    "year": "2019",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "GAMMA\\\u2014a high performance dataflow database machine",
    "authors": [
      "David J. DeWitt",
      "Goetz Graefe",
      "Krishna B. Kumar",
      "Robert H. Gerber",
      "Michael L. Heytens",
      "M. Muralikrishna"
    ],
    "year": "1988",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Performance Driven Database Design for Scalable Web Applications",
    "authors": [
      "Jozsef Patvarczki",
      "Murali Mani",
      "Neil Heffernan"
    ],
    "year": "2009",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "A comparative analysis of methodologies for database schema integration",
    "authors": [
      "C. Batini",
      "M. Lenzerini",
      "S. B. Navathe"
    ],
    "year": "1986",
    "type": "Publication",
    "count": 7,
    "editor": "Jannik Ott"
  },
  {
    "title": "A Comparison between Relational Databases and NoSQL Databases",
    "authors": [
      "Behjat U Nisa"
    ],
    "year": "2018",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "XML and relational database management systems: the inside story",
    "authors": [
      "Michael Rys",
      "Don Chamberlin",
      "Daniela Florescu"
    ],
    "year": "2005",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "The Claremont report on database research",
    "authors": [
      "Rakesh Agrawal",
      "Anastasia Ailamaki",
      "Philip A. Bernstein",
      "Eric A. Brewer",
      "Michael J. Carey",
      "Surajit Chaudhuri",
      "Anhai Doan",
      "Daniela Florescu",
      "Michael J. Franklin",
      "Hector Garcia-Molina",
      "Johannes Gehrke",
      "Le Gruenwald",
      "Laura M. Haas",
      "Alon Y. Halevy",
      "Joseph M. Hellerstein",
      "Yannis E. Ioannidis",
      "Hank F. Korth",
      "Donald Kossmann",
      "Samuel Madden",
      "Roger Magoulas",
      "Beng Chin Ooi",
      "Tim O'Reilly",
      "Raghu Ramakrishnan",
      "Sunita Sarawagi",
      "Michael Stonebraker",
      "Alexander S. Szalay",
      "Gerhard Weikum"
    ],
    "year": "2009",
    "type": "Publication",
    "count": 3,
    "editor": "Jannik Ott"
  },
  {
    "title": "Argonaute--a database for gene regulation by mammalian microRNAs.",
    "authors": [
      "Priyanka Shahi",
      "Serguei Loukianiouk",
      "Andreas Bohne-Lang",
      "Marc Kenzelmann",
      "Stefan K\u00fcffer",
      "Sabine Maertens",
      "Roland Eils",
      "Herrmann-Josef Gr\u00f6ne",
      "Norbert Gretz",
      "Benedikt Brors"
    ],
    "year": "2006",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Meta-Modeling to design the Structured Database Schema",
    "authors": [
      "Elvira Locuratolo"
    ],
    "year": "2006",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "SMPDB: The Small Molecule Pathway Database.",
    "authors": [
      "Alex Frolkis",
      "Craig Knox",
      "Emilia Lim",
      "Timothy Jewison",
      "Vivian Law",
      "David D. Hau",
      "Phillip Liu",
      "Bijaya Gautam",
      "Son Ly",
      "An Chi C. Guo",
      "Jianguo Xia",
      "Yongjie Liang",
      "Savita Shrivastava",
      "David S. Wishart"
    ],
    "year": "2010",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "RAIN: RNA-protein Association and Interaction Networks.",
    "authors": [
      "Alexander Junge",
      "Jan C. Refsgaard",
      "Christian Garde",
      "Xiaoyong Pan",
      "Alberto Santos",
      "Ferhat Alkan",
      "Christian Anthon",
      "Christian von Mering",
      "Christopher T. Workman",
      "Lars Juhl J. Jensen",
      "Jan Gorodkin"
    ],
    "year": "2017",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "LIGAND: chemical database of enzyme reactions",
    "authors": [
      "Susumu Goto",
      "Takaaki Nishioka",
      "Minoru Kanehisa"
    ],
    "year": "2000",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "ChEBI - Chemical Entities of Biological Interest",
    "authors": [
      "P. de Matos",
      "M. Ennis",
      "M. Zbinden",
      "A. McNaught",
      "R. Alc\u00e1ntara",
      "M. Darsow",
      "M. Guedj",
      "M. Ashburner",
      "K. Degtyarenko"
    ],
    "year": "2006",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "On replacing standard system error messages for relational database constraints with context aware natural language ones",
    "authors": [
      "Diana Christina Mancas"
    ],
    "year": "2023",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "PolyQ Database - an integrated database on polyglutamine diseases.",
    "authors": [
      "Bernardo Estevam",
      "Carlos A. Matos",
      "Cl\u00e9vio N\u00f3brega"
    ],
    "year": "2023",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "MEMOSys 2.0: an update of the bioinformatics database for genome-scale models and genomic data.",
    "authors": [
      "Stephan Pabinger",
      "Rene Snajder",
      "Timo Hardiman",
      "Michaela Willi",
      "Andreas Dander",
      "Zlatko Trajanoski"
    ],
    "year": "2014",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "An introduction to database systems",
    "authors": [
      "C. J Date"
    ],
    "year": "2004",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "DBGET/LinkDB: an integrated database retrieval system",
    "authors": [
      "W. Fujibuchi",
      "S. Goto",
      "H. Migimatsu",
      "I. Uchiyama",
      "A. Ogiwara",
      "Y. Akiyama",
      "M. Kanehisa"
    ],
    "year": "1998",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Introduction to Database Systems, An (8th Edition)",
    "authors": [
      "C.J. Date"
    ],
    "year": "2003",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Beginning Database Design Solutions (Wrox Programmer to Programmer)",
    "authors": [
      "Rod Stephens"
    ],
    "year": "2008",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "SABIO-RK--database for biochemical reaction kinetics.",
    "authors": [
      "Ulrike Wittig",
      "Renate Kania",
      "Martin Golebiewski",
      "Maja Rey",
      "Lei Shi",
      "Lenneke Jong",
      "Enkhjargal Algaa",
      "Andreas Weidemann",
      "Heidrun Sauer-Danzwith",
      "Saqib Mir",
      "Olga Krebs",
      "Meik Bittkowski",
      "Elina Wetsch",
      "Isabel Rojas",
      "Wolfgang M\u00fcller"
    ],
    "year": "2012",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Heterogeneous database integration in biomedicine.",
    "authors": [
      "W. Sujansky"
    ],
    "year": "2001",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Human Protein Reference Database--2009 update.",
    "authors": [
      "T. S. K. Prasad",
      "Renu Goel",
      "Kumaran Kandasamy",
      "Shivakumar Keerthikumar",
      "Sameer Kumar",
      "Suresh Mathivanan",
      "Deepthi Telikicherla",
      "Rajesh Raju",
      "Beema Shafreen",
      "Abhilash Venugopal",
      "Lavanya Balakrishnan",
      "Arivusudar Marimuthu",
      "Sutopa Banerjee",
      "Devi S. Somanathan",
      "Aimy Sebastian",
      "Sandhya Rani",
      "Somak Ray",
      "C. J. Harrys Kishore",
      "Sashi Kanth",
      "Mukhtar Ahmed",
      "Manoj K. Kashyap",
      "Riaz Mohmood",
      "Y. L. Ramachandra",
      "V. Krishna",
      "Abdul A. Rahiman",
      "Sujatha Mohan",
      "Prathibha Ranganathan",
      "Subhashri Ramabadran",
      "Raghothama Chaerkady",
      "Akhilesh Pandey"
    ],
    "year": "2009",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Coronavirus Immunotherapeutic Consortium Database.",
    "authors": [
      "Jarjapu Mahita",
      "Brendan Ha",
      "Anais Gambiez",
      "Sharon L. Schendel",
      "Haoyang Li",
      "Kathryn M. Hastie",
      "S. Moses Dennison",
      "Kan Li",
      "Natalia Kuzmina",
      "Sivakumar Periasamy",
      "Alexander Bukreyev",
      "Jennifer E. Munt",
      "Mary Osei-Twum",
      "Caroline Atyeo",
      "James A. Overton",
      "Randi Vita",
      "Hector Guzman-Orozco",
      "Marcus Mendes",
      "Mari Kojima",
      "Peter J. Halfmann",
      "Yoshihiro Kawaoka",
      "Galit Alter",
      "Luc Gagnon",
      "Ralph S. Baric",
      "Georgia D. Tomaras",
      "Tim Germann",
      "Daniel Bedinger",
      "Jason A. Greenbaum",
      "Erica Ollmann Saphire",
      "Bjoern Peters"
    ],
    "year": "2023",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Autoinhibited Protein Database: a curated database of autoinhibitory domains and their autoinhibition mechanisms.",
    "authors": [
      "Daeahn Cho",
      "Hyang-Mi Lee",
      "Ji Ah Kim",
      "Jae Gwang Song",
      "Su hee Hwang",
      "Bomi Lee",
      "Jinsil Park",
      "Kha Mong Tran",
      "Jiwon Kim",
      "Phuong Ngoc Lam Vo",
      "Jooeun Bae",
      "Teerapat Pimt",
      "Kangseok Lee",
      "J\u00f6rg Gsponer",
      "Hyung Wook Kim",
      "Dokyun Na"
    ],
    "year": "2024",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Properties of geothermal fluids in Switzerland: A new interactive database",
    "authors": [
      "Romain Sonney",
      "Fran\u00e7ois-D. Vuataz"
    ],
    "year": "2008",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Integrating compression and execution in column-oriented database systems",
    "authors": [
      "Daniel Abadi",
      "Samuel Madden",
      "Miguel Ferreira"
    ],
    "year": "2006",
    "type": "Publication",
    "count": 3,
    "editor": "Jannik Ott"
  },
  {
    "title": "Update of TTD: Therapeutic Target Database.",
    "authors": [
      "Feng Zhu",
      "BuCong Han",
      "Pankaj Kumar",
      "XiangHui Liu",
      "XiaoHua Ma",
      "Xiaona Wei",
      "Lu Huang",
      "YangFan Guo",
      "LianYi Han",
      "ChanJuan Zheng",
      "YuZong Chen"
    ],
    "year": "2010",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "A Analysis of Different Type of Advance database System For Data Mining Based on Basic Factor",
    "authors": [
      "Kamlesh Kumar Pandey",
      "Rajat Kumar Yadu",
      "Anshu Dwivedi",
      "Pradeep Kumar Shukla"
    ],
    "year": "2015",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "VFDB: a reference database for bacterial virulence factors.",
    "authors": [
      "Lihong Chen",
      "Jian Yang",
      "Jun Yu",
      "Zhijian Yao",
      "Lilian Sun",
      "Yan Shen",
      "Qi Jin"
    ],
    "year": "2005",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "Strategic Database Security Management and Cybercrime Reduction among Youths in Information Technology Companies in Nigeria",
    "authors": [
      "Agbeche Aaron | Elechi Bobby Chime | Okechukwu Prince Jumbo"
    ],
    "year": "2021",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "Human immunodeficiency virus type 1, human protein interaction database at NCBI",
    "authors": [
      "William Fu",
      "Brigitte E. Sanders-Beer",
      "Kenneth S. Katz",
      "Donna R. Maglott",
      "Kim D. Pruitt",
      "Roger G. Ptak"
    ],
    "year": "2009",
    "type": "Publication",
    "count": 2,
    "editor": "Jannik Ott"
  },
  {
    "title": "A prospective multicentre otology database",
    "authors": [
      "M Yung",
      "P v Heyning"
    ],
    "year": "2007",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {
    "title": "HOFE: an interactive forensic entomological database.",
    "authors": [
      "Mandie Liu",
      "Yihong Qu",
      "Yifei Luo",
      "Binta J. J. Jallow",
      "Yuting Ma",
      "Afito Luciano",
      "Jingjing Huang",
      "Jifeng Cai",
      "Fanming Meng"
    ],
    "year": "2024",
    "type": "Publication",
    "count": 1,
    "editor": "Jannik Ott"
  },
  {